config_name: "dataset_tid2008"

app_version: "0.1.1"

dataset:
  representative_name: "TID2008"
  name: "tid2008"
  original_image_size:
    width: 512
    height: 384
  images:
    reference:
      path: "datasets/tid2008/reference_images/"
      count: 25
    distorted:
      path: "datasets/tid2008/distorted_images/"
      count: 1700
  quality_label:
    type: "mos"
    min: 0
    max: 9
  labels_path: "datasets/tid2008/mos_with_names.txt"
