config_name: "dataset_kadid10k"

app_version: "0.1.2"

dataset:
  representative_name: "KADID-10k"
  name: "kadid10k"
  original_image_size:
    width: 512
    height: 384
  images:
    reference:
      path: "datasets/kadid10k/images/"
      count: 81
    distorted:
      path: "datasets/kadid10k/images/"
      count: 10125
  quality_label:
    type: "mos"
    min: 1
    max: 5
  labels_path: "datasets/kadid10k/dmos.csv"
