config_name: "tid2008_vit_base_patch16_224_baseline"

app:
  version: "0.1.1"

dataset:
  representative_name: "TID2008"
  name: "tid2008"
  original_image_size:
    width: 512
    height: 384
  images:
    reference:
      path: "datasets/tid2008/reference_images/"
      count: 25
    distorted:
      path: "datasets/tid2008/distorted_images/"
      count: 1700
  quality_label:
    type: "mos"
    min: 0
    max: 9
  labels_path: "datasets/tid2008/mos_with_names.txt"

model:
  name: "vit_base_patch16_224"
  input:
    type: "images"
    num_of_images: 2
    have_same_image_size: true
    are_images_square: true
    image_size:
      width: 224
      height: 224
    keep_original_aspect_ratio: true
  embedding_dimension: 768
  output:
    type: "unified_quality_score"
    min: 0
    max: 1

training:
  quality_label:
    type: "unified_quality_score"
    min: 0
    max: 1
  splits:
    train: 0.6
    validation: 0.2
    test: 0.2
    random_seed: 42
  batch_size: 8
  num_of_epochs: 100
  early_stopping:
    enabled: false
    max_epochs_without_improvement: 5
    min_improvement_delta: 0.001
  learning_rate: 0.0001
  device: "cuda"
  num_of_workers: 4

checkpointing:
  enabled: true
  save_every_n_epochs: 20
  save_last_epoch: true
  save_best_epoch: true

logging:
  tensorboard: true
