config_name: "kadid10k_vit_base_patch16_224_baseline"

dataset:
  representative_name: "KADID-10k"
  name: "kadid10k"
  images_path: "datasets/kadid10k/images"
  labels_path: "datasets/kadid10k/dmos.csv"
  train_split: 0.8
  batch_size: 8
  input_size: 224

model:
  name: "vit_base_patch16_224"
  embedding_dimension: 768

training:
  num_of_epochs: 5
  learning_rate: 0.0001
  computation_unit: "cuda"
  num_of_workers: 4

logging:
  tensorboard: true
  save_checkpoint_every: 1
