experiment_name: "exp_tid2013_baseline"

dataset:
  name: "TID2013"
  type: "tid2013"
  images_path: "datasets/tid2013/distorted_images"
  labels_path: "datasets/tid2013/mos.txt"
  train_split: 0.8
  batch_size: 8
  input_size: 224

model:
  name: "vit_base_patch16_224"
  embedding_dimension: 768

training:
  num_of_epochs: 5
  learning_rate: 0.0001
  computation_unit: "cuda"
  num_of_workers: 4

logging:
  tensorboard: true
  save_checkpoint_every: 1
  checkpoints_path: "experiments/checkpoints/tid2013_baseline"
