config_name: "kadid10k_vit_base_patch16_224_baseline"

app:
  version: "0.1.1"

dataset:
  representative_name: "KADID-10k"
  name: "kadid10k"
  original_image_size:
    width: 512
    height: 384
  images:
    reference:
      path: "datasets/kadid10k/images/"
      count: 81
    distorted:
      path: "datasets/kadid10k/images/"
      count: 10125
  quality_label:
    type: "dmos"
    min: 1
    max: 5
  labels_path: "datasets/kadid10k/dmos.csv"

model:
  name: "vit_base_patch16_224"
  input:
    type: "images"
    num_of_images: 2
    have_same_image_size: true
    are_images_square: true
    image_size:
      width: 224
      height: 224
    keep_original_aspect_ratio: true
  embedding_dimension: 768
  output:
    type: "inverted_normalized_dmos"
    min: 0
    max: 1

training:
  quality_label:
    type: "inverted_normalized_dmos"
    min: 0
    max: 1
  splits:
    train: 0.6
    validation: 0.2
    test: 0.2
    random_seed: 42
  batch_size: 8
  num_of_epochs: 5
  early_stopping:
    enabled: false
    max_epochs_without_improvement: 5
    min_improvement_delta: 0.001
  learning_rate: 0.0001
  device: "cuda"
  num_of_workers: 4

checkpointing:
  enabled: true
  save_every_n_epochs: 1
  save_last_epoch: true
  save_best_epoch: true

logging:
  tensorboard: true
